version: '3.3'
services:
  app:
<<<<<<< HEAD
    image: ghcr.io/${{ github.repository_owner }}/my-app:latest
    command:
      - /bin/bash
=======
    image: ghcr.io/${{ github.repository_owner }}/my-app:latest
>>>>>>> 12566f1 (update docker-compose.yml)
