name: build,deploy project 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.MY_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:latest

      - name: Docker compose up
        run: |
           docker pull ghcr.io/${{ github.repository }}/my-app:latest
           docker-copmose down
           docker-copmose up -d
