name: build,deploy project 

on:
  push:
    branches:
      - main


jobs:
  build-and-push:
    runs-on: self-hosted

    steps:

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Build Docker image
        run: |
          sudo docker build -t ghcr.io/${{ github.repository_owner }}/my-app:latest .

      - name: Push Docker image
        run: |
          sudo docker push ghcr.io/${{ github.repository_owner }}/my-app:latest

      - name: Docker compose up
        run: |
          sudo docker pull ghcr.io/${{ github.repository_owner }}/my-app:latest
          sudo docker copmose down
          sudo docker copmose up -d
